### ISSUE TITLE
Update Clara install user references to point to Ansible install vs using Bootstrap

### ISSUE THREAD

**Issue by slbryson** [NVIDIA/clara-dicom-adapter#85]
### Description
Starting in Clara 0.7.3 and mandatory in Clara 0.8.1 the installation/uninstallation method for Clara uses Ansible scriptis and bootstrap is no longer supported in 0.8.1
### Steps to reproduce
Please share a clear and concise description of the problem.
1. In the Setup.md section the recommendation to install Clara reference bootstrap.
...

### Expected behavior
Expect that it will reference the Ansible script package on NGC or the new link consistent in Clara 0.8.1 documentation
### Actual behavior
A clear and concise description of what actually happened.

**Comment by mocsharp** [comment]
Previously fixed in https://github.com/NVIDIA/clara-dicom-adapter/pull/80
